package View;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.util.List;
import Controller.UserManager;
import Model.*;

/**
 * AdminFrame is a GUI window for managing users in the admin panel.
 * Provides functionality to view, search, delete, and sort users.
 */
public class AdminFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminFrame.class.getName());
    // Table to display users
    private JTable userTable;
    // Text field for searching users
    private JTextField txtSearch;
    // Buttons for delete, delete all, and sort actions
    private JButton btnDelete, btnDeleteAll, btnSort;
    // User manager for handling user operations
    private UserManager userManager;
    // List of users
    private List<User> users;

    /**
     * Creates new form AdminFrame (default constructor for form editor).
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * Constructs an AdminFrame with the given UserManager.
     * Initializes the GUI components and sets up event listeners.
     * @param userManager the user manager for user operations
     */
    public AdminFrame(UserManager userManager) {
        this.userManager = userManager;
        users = userManager.loadUsers();

        setTitle("Admin Panel");
        setSize(600, 400);
        setLayout(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        userTable = new JTable(new DefaultTableModel(new Object[]{"Name","Email","Password"},0));
        JScrollPane scrollPane = new JScrollPane(userTable);
        scrollPane.setBounds(20, 50, 550, 200);
        add(scrollPane);

        txtSearch = new JTextField();
        txtSearch.setBounds(20, 10, 200, 25);
        add(txtSearch);

        btnDelete = new JButton("Delete Selected");
        btnDelete.setBounds(20, 270, 150, 30);
        add(btnDelete);

        btnDeleteAll = new JButton("Delete All");
        btnDeleteAll.setBounds(200, 270, 150, 30);
        add(btnDeleteAll);

        btnSort = new JButton("Sort by Name");
        btnSort.setBounds(380, 270, 150, 30);
        add(btnSort);

        refreshUserTable(users);

        // Search functionality
        txtSearch.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                String keyword = txtSearch.getText();
                List<User> filtered = userManager.searchUser(keyword, users);
                refreshUserTable(filtered);
            }
        });

        // Delete single user
        btnDelete.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int row = userTable.getSelectedRow();
                if(row >= 0) {
                    String name = userTable.getValueAt(row, 0).toString();
                    userManager.deleteUser(name, users);
                    refreshUserTable(users);
                } else {
                    JOptionPane.showMessageDialog(null, "Select a user to delete!");
                }
            }
        });

        // Delete all users
        btnDeleteAll.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int confirm = JOptionPane.showConfirmDialog(null, "Are you sure?", "Confirm", JOptionPane.YES_NO_OPTION);
                if(confirm == JOptionPane.YES_OPTION) {
                    userManager.deleteAllUsers(users);
                    refreshUserTable(users);
                }
            }
        });

        // Sort users
        btnSort.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                userManager.sortUsersByName(users);
                refreshUserTable(users);
            }
        });
    }

    /**
     * Refreshes the user table with the given list of users.
     * @param usersToShow the list of users to display
     */
    private void refreshUserTable(List<User> usersToShow) {
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.setRowCount(0);
        for(User u : usersToShow) {
            model.addRow(new Object[]{u.getName(), u.getEmail(), u.getPassword()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UserManager um = new UserManager();
        new AdminFrame(um).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
