/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProjectsController;
import Controller.CurrentUserController;
import Model.Project;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.nio.file.ProviderMismatchException;

/**
 *
 * @author USER
 */
public class ProjectsFrame extends javax.swing.JFrame {
    
 private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjectsFrame.class.getName());

    private ProjectsController projectController;
    private CurrentUserController userController;

    private JPopupMenu projectPopup;
    private JMenuItem renameItem;
    private JMenuItem deleteItem;
    
    /**
     *
     * @param userCtrl
     * @param projCtrl
     */
    public ProjectsFrame(CurrentUserController userCtrl, ProjectsController projCtrl) {
               this.userController = userCtrl;
        this.projectController = projCtrl;

        initComponents();

        projectController.loadFromFile();
        loadTable();
        setupPopupMenu();
        attachTableMouseListener();
    }
    private void setupPopupMenu() {
        projectPopup = new JPopupMenu();
        renameItem = new JMenuItem("Rename");
        deleteItem = new JMenuItem("Delete");

        projectPopup.add(renameItem);
        projectPopup.add(deleteItem);

        renameItem.addActionListener(e -> renameSelectedProject());
        deleteItem.addActionListener(e -> deleteSelectedProject());
    }
    
    private void attachTableMouseListener() {
        projectsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent e) { handlePopup(e); }
            public void mouseReleased(java.awt.event.MouseEvent e) { handlePopup(e); }

            private void handlePopup(java.awt.event.MouseEvent e) {
                if (e.isPopupTrigger()) {
                    int row = projectsTable.rowAtPoint(e.getPoint());
                    if (row != -1) {
                        projectsTable.setRowSelectionInterval(row, row);
                        projectPopup.show(e.getComponent(), e.getX(), e.getY());
                    }
                }
            }
        });
    }
    private void loadTable() {
        DefaultTableModel model = (DefaultTableModel) projectsTable.getModel();
        model.setRowCount(0);
        for (Project p : projectController.getProjects()) {
            model.addRow(new Object[]{p.getName(), "0 KB", p.getPath(), "Open"});
        }
    }

    private void createProject() {
        String name = JOptionPane.showInputDialog(this, "Enter Project Name");
        if (name == null || name.trim().isEmpty()) return;

        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) return;

        Project p = projectController.createProject(name, chooser.getSelectedFile());
        DefaultTableModel model = (DefaultTableModel) projectsTable.getModel();
        model.addRow(new Object[]{p.getName(), "0 KB", p.getPath(), "Open"});
    }
    
    
    private void renameSelectedProject() {
        int row = projectsTable.getSelectedRow();
        if (row == -1) return;

        String newName = JOptionPane.showInputDialog(this, "Enter new project name");
        if (newName == null || newName.trim().isEmpty()) return;

        projectController.renameProject(row, newName);
        loadTable();
    }

    
    private void deleteSelectedProject() {
        int row = projectsTable.getSelectedRow();
        if (row == -1) return;

        int confirm = JOptionPane.showConfirmDialog(this, "Delete selected project?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            projectController.deleteProject(row);
            loadTable();
        }
    }
    
        private void showPanel(JPanel panelToShow) {
        ProjectsPanel.setVisible(false);
        FavouritesPanel.setVisible(false);
        TrashPanel.setVisible(false);

        panelToShow.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        createProjectButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        projectsButton = new javax.swing.JButton();
        favouritesButton = new javax.swing.JButton();
        trashButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        ProjectsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectsTable = new javax.swing.JTable();
        FavouritesPanel = new javax.swing.JPanel();
        TrashPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        panel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(44, 44, 44));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 30, 30));

        jPanel1.setBackground(new java.awt.Color(44, 44, 44));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        jPanel6.setBackground(new java.awt.Color(44, 44, 44));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/2DLogo.png"))); // NOI18N
        jButton5.setText("jButton5");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6);

        jPanel3.add(jPanel1);

        createProjectButton.setBackground(new java.awt.Color(179, 156, 208));
        createProjectButton.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        createProjectButton.setText("+ Create Project");
        createProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectButtonActionPerformed(evt);
            }
        });
        jPanel3.add(createProjectButton);

        jPanel5.setBackground(new java.awt.Color(44, 44, 44));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jButton7.setBackground(new java.awt.Color(44, 44, 44));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/plus.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);

        jButton2.setBackground(new java.awt.Color(44, 44, 44));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bell.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/profile.png"))); // NOI18N
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(jButton9);

        jPanel3.add(jPanel5);

        panel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(79, 78, 78));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        projectsButton.setText("Projects");
        projectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(projectsButton, gridBagConstraints);

        favouritesButton.setText("Favourites");
        favouritesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favouritesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel4.add(favouritesButton, gridBagConstraints);

        trashButton.setText("Trash");
        trashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trashButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 853, 0);
        jPanel4.add(trashButton, gridBagConstraints);

        panel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel7.setBackground(new java.awt.Color(44, 44, 44));
        jPanel7.setLayout(new java.awt.CardLayout());

        ProjectsPanel.setBackground(new java.awt.Color(44, 44, 44));

        jLabel1.setText("Projects");

        projectsTable.setBackground(new java.awt.Color(44, 44, 44));
        projectsTable.setForeground(new java.awt.Color(255, 255, 255));
        projectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project Name", "Project Size", "Project Directory", "Open Project"
            }
        ));
        projectsTable.setColumnSelectionAllowed(true);
        projectsTable.setGridColor(new java.awt.Color(204, 204, 204));
        projectsTable.setSelectionForeground(new java.awt.Color(44, 44, 44));
        projectsTable.setShowGrid(true);
        jScrollPane1.setViewportView(projectsTable);
        projectsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout ProjectsPanelLayout = new javax.swing.GroupLayout(ProjectsPanel);
        ProjectsPanel.setLayout(ProjectsPanelLayout);
        ProjectsPanelLayout.setHorizontalGroup(
            ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ProjectsPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ProjectsPanelLayout.setVerticalGroup(
            ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(899, Short.MAX_VALUE))
        );

        jPanel7.add(ProjectsPanel, "card2");

        FavouritesPanel.setBackground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout FavouritesPanelLayout = new javax.swing.GroupLayout(FavouritesPanel);
        FavouritesPanel.setLayout(FavouritesPanelLayout);
        FavouritesPanelLayout.setHorizontalGroup(
            FavouritesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
        );
        FavouritesPanelLayout.setVerticalGroup(
            FavouritesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1153, Short.MAX_VALUE)
        );

        jPanel7.add(FavouritesPanel, "card3");

        TrashPanel.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout TrashPanelLayout = new javax.swing.GroupLayout(TrashPanel);
        TrashPanel.setLayout(TrashPanelLayout);
        TrashPanelLayout.setHorizontalGroup(
            TrashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
        );
        TrashPanelLayout.setVerticalGroup(
            TrashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1153, Short.MAX_VALUE)
        );

        jPanel7.add(TrashPanel, "card4");

        panel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel1, "card2");

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectButtonActionPerformed

      createProject(); // TODO add your handling code here:
    }//GEN-LAST:event_createProjectButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void projectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectsButtonActionPerformed
        showPanel(ProjectsPanel);

        // TODO add your handling code here:
    }//GEN-LAST:event_projectsButtonActionPerformed

    private void favouritesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favouritesButtonActionPerformed
       showPanel(FavouritesPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_favouritesButtonActionPerformed

    private void trashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trashButtonActionPerformed
        
        showPanel(TrashPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_trashButtonActionPerformed

    /**
     *
     * @param args
     */
    public static void main(String[] args) {
        CurrentUserController userCtrl = new CurrentUserController();
        userCtrl.login("Bikram");  // "Bikram" is the username for testing

        // Create ProjectsController for this user
        ProjectsController projCtrl = new ProjectsController(userCtrl);

        // Create the ProjectsFrame with the controllers
        javax.swing.SwingUtilities.invokeLater(() -> {
            ProjectsFrame frame = new ProjectsFrame(userCtrl, projCtrl);
            frame.setVisible(true);
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FavouritesPanel;
    private javax.swing.JPanel ProjectsPanel;
    private javax.swing.JPanel TrashPanel;
    private javax.swing.JButton createProjectButton;
    private javax.swing.JButton favouritesButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private javax.swing.JButton projectsButton;
    private javax.swing.JTable projectsTable;
    private javax.swing.JButton trashButton;
    // End of variables declaration//GEN-END:variables
}
